apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-cache
  namespace: my-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 50Gi
